#Project ID: taxform-generator 
#Project Number: 
#Address: http://taxform-generator.appspot.com/
#Author: Vi Nguyen
#Service Account Name: taxform-generator@appspot.gserviceaccount.com
#Client ID: 
#Client Secret: 

application: taxform-generator
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: app.application

